### ISSUE TITLE
[Bug] Unexpected warning: Failed prop type: minWidth larger than item width/maxWidth

### ISSUE THREAD

**Issue by eamaya2008** [react-grid-layout/react-grid-layout#1479] opened 2021-05-24 23:22 UTC
[Bug] Unexpected warning: Failed prop type: minWidth larger than item width/maxWidth

**Comment by STRML** [comment] 2021-05-24 23:27
This is not a bug. Check the props you passed in. If you set a min width or height that is larger than your set width or height (or max) it creates an impossible situation.

**Comment by STRML** [comment] 2021-05-24 23:28
Closing as a duplicate of #493

**Closed** 2021-05-24 23:28 UTC

**Comment by eamaya2008** [comment] 2021-05-24 23:38
Dear,
here is my item. Can you help me?

It happens when I bring the window to the minimum width.

layout: { i: '', x: 0, y: 0, w: 3, h: 3, minW: 2, minH: 2, maxW: 6, maxH: 6}


Esteban Amaya
Full Stack Web Developer
02616864623

________________________________
De: Samuel Reed ***@***.***>
Enviado: lunes, 24 de mayo de 2021 20:27
Para: react-grid-layout/react-grid-layout ***@***.***>
Cc: eamaya2008 ***@***.***>; Author ***@***.***>
Asunto: Re: [react-grid-layout/react-grid-layout] [Bug] Unexpected warning: Failed prop type: minWidth larger than item width/maxWidth (#1479)


This is not a bug. Check the props you passed in. If you set a min width or height that is larger than your set width or height (or max) it creates an impossible situation.
