### ISSUE TITLE
onDrag, onDragStop in React 18

### ISSUE THREAD

**Issue by sashako54** [react-grid-layout/react-grid-layout#1745] opened 2022-07-05 14:25 UTC
### Describe the bug

in react 18 if you trigger events onDrag + onDragStop quickly setState from onDrag will not happened, so we won't get placeholder in activeDrag and in onDragStop we won't have activeDrag. 

This case will freaze react-grid-layout, becouse onDragStop will just return undefined.

It happens because in React 18 we have batching. 
https://github.com/reactwg/react-18/discussions/21

So we can use flushSync from react-dom to resolve this propblem.

`
ReactDom.flushSync(() => setState(...))
`

this will force rerender and will fix this bug. 

### Your Example Website or App

my local app

### Steps to Reproduce the Bug or Issue

1. use react 18
2. use throttle cpu
3. quickly trigger onDrag + onDragStop events

### Expected behavior

onDrag + onDragStop works without friezes

### react-grid-layout library version

last

### Operating System Version

all

### Browser

Chrome

**Comment by peteranderss0n** [comment] 2022-07-15 10:59
Can confirm I also have this issue with React 18

**Comment by JuliusMorkunas** [comment] 2022-09-15 12:51
Are there any plans to merge #1746 and #1774 into the main branch and release a new version with React 18 support in the near future?

**Comment by Brandontam29** [comment] 2022-10-28 02:24
Any updates?

**Comment by n-junge** [comment] 2022-11-21 08:56
Can confirm this issue. Is this worked on? The required code changes seem to be minimal

**Comment by NikitaAnntonenko** [comment] 2023-02-09 10:29
Could someone merge the PR? It will be really helpful with migration to react 18

**Comment by lights-a5** [comment] 2023-02-14 21:16
Also having this issue. Would like this fixed soon too.

**Comment by patrick-bloomerang** [comment] 2023-03-28 20:37
Would love to see this get merged in to support those on React 18!

**Comment by tantawyk** [comment] 2023-08-25 16:03
I have the same problem with React 17, it happens when you simply click the drag handle, this triggers the onDragStart and doesn't trigger the onDragStop because there's no activeDrag happened.

I also moved to React 18 and added the code from @sashako54 with flushSync, and the same problem still happens.

I opened a [PR](https://github.com/react-grid-layout/react-grid-layout/pull/1923) to solve this, please provide feedback.

**Comment by tzimmermann** [comment] 2023-09-26 14:12
Also seeing this issue since upgrading to React 18.
@STRML Are there any plans to fix this bug to make react-grid-layout compatible with React 18?
I quickly checked and this bug is still reproducible 

- with the latest `react-grid-layout@1.4.2`.
- with the fix from https://github.com/react-grid-layout/react-grid-layout/pull/1923 (so this seems to be another issue that is also not React 18 related, as @tantawyk also pointed out).

I was **not** able to reproduce it any more with the fix from https://github.com/react-grid-layout/react-grid-layout/pull/1746 applied.I had to create an updated fork to be able to test it.

Feel free to take a look and possibly merge: https://github.com/react-grid-layout/react-grid-layout/pull/1947

**Comment by magyarp** [comment] 2023-10-30 21:28
> Also seeing this issue since upgrading to React 18. @STRML Are there any plans to fix this bug to make react-grid-layout compatible with React 18? I quickly checked and this bug is still reproducible
> 
>     * with the latest `react-grid-layout@1.4.2`.
> 
>     * with the fix from [fix: set activeDrag in the state onDragStart #1923](https://github.com/react-grid-layout/react-grid-layout/pull/1923) (so this seems to be another issue that is also not React 18 related, as @tantawyk also pointed out).
> 
> 
> I was **not** able to reproduce it any more with the fix from #1746 applied.I had to create an updated fork to be able to test it.
> 
> Feel free to take a look and possibly merge: #1947

Thank you @tzimmermann, I also don't experience this grid freezing issue after your fix.

**Comment by STRML** [comment] 2023-10-31 15:48
Trying to chase this down, see if you can replicate it in `master`.

**Comment by magyarp** [comment] 2023-11-02 09:51
> Trying to chase this down, see if you can replicate it in `master`.

The issue is gone in our case, thank you very much!

**Comment by tzimmermann** [comment] 2023-11-06 08:37
> Trying to chase this down, see if you can replicate it in `master`.

I can also confirm that the issue is resolved on latest master, thank you! Looking forward to see it released soon.

**Comment by STRML** [comment] 2023-11-08 18:27
Ok. I've published the fix as `1.4.3` and will close this. Please comment if `1.4.3` does not fix your issue.

**Closed by STRML** 2023-11-08 18:27 UTC
