### ISSUE TITLE
upgrade to 1.2.3 causes grid to not render at all

### ISSUE THREAD

**Issue by delashum** [react-grid-layout/react-grid-layout#1428] opened 2021-03-17 21:14 UTC
I don't have a sandbox for this, but updating from `1.2.2` to `1.2.3` causes the grid to not render at all now in my app. Confirmed that downgrading to `1.2.2` again fixes things. I am using `WidthProvider(GridLayout)`. There are no build errors with typescript.

The container div that this lib usually renders which has `class="react-grid-layout"` with all the `react-grid-item`s underneath it is now just `<div></div>`. I will try to update this thread as I find more, but just wanted to notify that `1.2.3` appears to have breaking changes.

**Comment by delashum** [comment] 2021-03-17 21:17
Closing for now, as I may have found something else causing the issue. Will re-open if needed

**Comment by delashum** [comment] 2021-03-17 21:36
Here's a sandbox. Was able to repro. If you change the version of `react-grid-layout` to `1.2.3` you will see it completely fails to render the grid, where `1.2.2` works fine

https://codesandbox.io/s/ecstatic-microservice-9t0ej

**Comment by STRML** [comment] 2021-03-17 21:55
Thanks. The issue is the `measureBeforeMount` property, which broke with the `ref` change. Will push a patch shortly.

**Comment by delashum** [comment] 2021-03-17 21:57
Great, thanks. Let me know if there's anything I can do to help

**Comment by STRML** [comment] 2021-03-18 16:08
Fixed in 1.2.4 which is now live.

**Closed** 2021-03-18 16:07 UTC
